id: PEA8F5C18
initial_creation_type: input
source_metadata:
  title: Rendawa Series
  language: en
  description: 'Texts by and about Rendawa Shönnu Lodrö (red mda'' ba gzhon nu blo
    gros, 1349–1412), the famed Sakya scholar and teacher of Tsongkhapa Lobzang Drakpa:'
  volume:
    6a96219b8d234c0cb668319143ccccd2:
      title: Prayer to Rendawa Shönnu Lodrö
      parent: Prayers
created_at: '2022-03-01T01:20:30.874463'
last_modified_at: '2022-03-01T01:20:30.874469'
